[package]
name = "TotkBits"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zstd = "0.13"
roead = { version = "0.23.1", features = ["yaml","sarc","byml"] }
serde = "1.0"
serde_json = "1.0"
egui = "0.15"
eframe = "0.15"
nfd = "0.0.4" #openfiledialog
native-dialog = "0.7.0"